### ISSUE TITLE
Values is combined with the wrong header

### ISSUE THREAD

**Issue by hmazter** [spatie/simple-excel#14]
I have noticed that the values from `\Box\Spout\Common\Entity\Row::toArray` is not always sorted numerically.
And when they are not sorted and then combined with the header, wrong header is applied to the wrong value.

For example, when running this code:
```php
$rows = SimpleExcelReader::create($tempfile)->noHeaderRow()->getRows();
foreach ($rows as $index => $values) {
    dump($values);
}
```
One of the rows dumps as this:
![Screenshot 2019-10-30 at 15 36 08](https://user-images.githubusercontent.com/805377/67867964-811f7a00-fb2b-11e9-84b6-64ff19cd371e.png)
Which is not sorted numerically and therefore header with index 2 is applied to the value with index 3.

I think this can be solved by using `ksort` on the values in `\Spatie\SimpleExcel\SimpleExcelReader::getValueFromRow`

**Comment by freekmurze** [comment]
We'll continue this conversation in #15
