### ISSUE TITLE
Testing download response

### ISSUE THREAD

**Issue by chrisrhymes** [spatie/simple-excel#17]
How would you test a file created with simple excel that is then returned via a download response? Is this possible? 

Below is some example code to help explain the scenario and the `$response->???` is what I am unsure about.

```php
// ExportController.php

SimpleExcelWriter::create($this->file)
            ->addRow([
                'first_name' => 'John',
                'last_name' => 'Doe',
            ]);
return response()->download($this->file);
``` 

```php
// ExportTest.php

$response = $this->get('/export/path/');
$rowCount = SimpleExcelReader::create($response->???)
            ->getRows()
            ->count();

$this->assertEquals(1, $rowCount);
```

Thanks.

**Comment by freekmurze** [comment]
This question is out of scope for this package. Best to ask this on a forum like Laracasts.

**Comment by freekmurze** [comment]
I've added support for streaming downloads to the browser. 
https://github.com/spatie/simple-excel#streaming-an-excel-file-to-the-browser

Due to the way this works (the php process is ended immediately after the download) you can't write a test around this.
