### ISSUE TITLE
Bulk write export using addRows 

### ISSUE THREAD

**Issue by vinithanv** [spatie/simple-excel#22]
$writer = SimpleExcelWriter::create($pathToCsv)
     ->addRow([
        'first_name' => 'John',
        'last_name' => 'Doe',
    ])
    ->addRow([
        'first_name' => 'Jane',
        'last_name' => 'Doe',
    ]);

How can I use multiple arrays on this addRow when I write more than 1000 records to write its getting more time can you suggest any feature is there to use multiple arrays on addRow

am using a package of 1.2.2

I need to use Box\Spout\Writer\WriterInterface; addRows method with simple-excel like below

$writer = SimpleExcelWriter::create($pathToCsv)
     ->addRows([
        'first_name' => 'John',
        'last_name' => 'Doe',
    ],[
        'first_name' => 'Jane',
        'last_name' => 'Doe',
    ]);

**Comment by freekmurze** [comment]
Feel free to PR that adds `addRows` to the package. Make sure to include tests.
