### ISSUE TITLE
SimpleExcelWriter class is missing the useDelimiter method

### ISSUE THREAD

**Issue by galkrisztina** [spatie/simple-excel#24]
I would like to call the `useDelimiter` method on the `SimpleExcelWriter` class, but the method is undefined on the writer. (You give an example in the readme file how to call it on the writer, but the method is undefined: `SimpleExcelWriter::create($pathToCsv)->useDelimiter(';');`).

I noticed that the method is defined in the `SimpleExcelReader`, I used that on my reader, and after that I extended your `SimpleExcelWriter` class to define also in there the method. 

Can you please put the missing `useDelimiter` also in the `SimpleExcelWriterClass` so that I can use it without needing to extend it?

Thanks!

**Comment by freekmurzetest** [comment]
Feel free to send a PR for this, make sure to include tests 👍

**Comment by freekmurze** [comment]
⏫ this was posted by the real me (was logged in via a test account)

**Comment by freekmurze** [comment]
Handled in #25
