### ISSUE TITLE
Read file from storage URL (S3)

### ISSUE THREAD

**Issue by ianfortier** [spatie/simple-excel#27]
Is it possible to read the file from a Storage path (Eg: S3)

I tried 
```
SimpleExcelReader::create(Storage::disk('s3')->path('xxxx.csv))->getRows();
SimpleExcelReader::create(Storage::disk('s3')->readStream('xxxx.csv))->getRows();
SimpleExcelReader::create(Storage::disk('s3')->url('xxxx.csv))->getRows();
```

Thank you

**Comment by freekmurze** [comment]
This package only works for local files.

**Comment by fwartner** [comment]
Any plans to support other filesystems? E.g. for Vapor-Usage?

**Comment by freekmurze** [comment]
Nope, feel free to PR functionality.

**Comment by ankurk91** [comment]
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

We must be able to supply s3 URL like
```
s3://bucket-name/path/file.ext
```

**Comment by ankurk91** [comment]
The underlying openspot package itself does not support stream while importing excel sheets
