### ISSUE TITLE
getRows() returns null after being called once

### ISSUE THREAD

**Issue by Francismori7** [spatie/simple-excel#36]
L: 8.9.0

Hey there,

Seems like a regression. Before, I was calling `->getRows()->first()` three times to check the header contents of three columns.

Now, the two second calls both return `null`.

Also, I was checking for duplicates using `->getRows()->uniqueStrict()` which works fine, but then, after that, I need to renew the `SimpleExcelReader` instance to be able to process the file.

I'll take a look in the commits to see what's happening.

**Comment by Francismori7** [comment]
@spatie Reversing those lines fixes my issue:

https://github.com/spatie/simple-excel/commit/a73bb309c1f08f0462919efe34ec48b7687bdabc#diff-b3b32a45bf2d4ad6a8588e4d3033f5c1R110-R113

**Comment by freekmurze** [comment]
@Francismori7 could you send a PR for this?

**Comment by Francismori7** [comment]
> @Francismori7 could you send a PR for this?

Of course! I'll get on it tomorrow.

**Comment by ahallhognason** [comment]
> > @Francismori7 could you send a PR for this?
> 
> Of course! I'll get on it tomorrow.

Sorry, I fixed this while at work and didn't push it until I got home. Sorry if you wanted to tackle this.

**Comment by Francismori7** [comment]
> > > @Francismori7 could you send a PR for this?
> > 
> > Of course! I'll get on it tomorrow.
> 
> Sorry, I fixed this while at work and didn't push it until I got home. Sorry if you wanted to tackle this.

That's perfect, I'm happy as long as anyone corrects this. I love open source.
