### ISSUE TITLE
Feature Request: Define header row

### ISSUE THREAD

**Issue by SkHCrusher** [spatie/simple-excel#38]
There are more and more services which do not output a clean format in the first lines of a CSV.

Here the actual content with headings starts only from one line "X".

In the current version of this library the header line is always the first one, even if I skip lines with the skip command.

It would be great if you could also specify the line where the heading is located.

Example csv:
```
"Account:";"1234567890";

"From:";"04.09.2020";
"To:";"04.10.2020";

"ColA";"ColB";"ColC";"ColD";
"ValA";"ValB";"ValC";"ValD";
"ValA";"ValB";"ValC";"ValD";
"ValA";"ValB";"ValC";"ValD";
"ValA";"ValB";"ValC";"ValD";
"ValA";"ValB";"ValC";"ValD";
"ValA";"ValB";"ValC";"ValD";
```

With the following command
```php
$rows = SimpleExcelReader::create($file->path())
  ->useDelimiter(';')
  ->skip(3)
  ->getRows();

$rows->each(function(array $rowProperties) {
  dd($rowProperties);
});
```

I get the following value:
```
array:3 [▼
  "Account:" => "ValA"
  1234567890 => "ValB"
  "" => "ValC"
]
```

But I would have expected:
```
array:5 [▼
  "ColA" => "ValA"
  "ColB" => "ValB"
  "ColC" => "ValC"
  "ColD" => "ValD"
]
```

Possibly with the following extension:
`->headerInRow(3)`

Thank you

**Comment by freekmurze** [comment]
Feel free to PR this. Make sure to include tests and an updated readme. Maybe use `headerOnRow`, that sounds better to me.
