### ISSUE TITLE
loop throw stdClass array

### ISSUE THREAD

**Issue by agobari** [spatie/simple-excel#50]
```
  $users = DB::table('users')
              ->join('delegates', 'users.user_id', '=', 'delegates.user_id')
              ->select('users.user_first_name_ar','users.user_second_name_ar','users.user_third_name_ar','users.user_last_name_ar', 'delegates.country as delegates_country', 'delegates.province as delegates_province')
            ->get()->toArray();
        
        $writer = SimpleExcelWriter::streamDownload('delegates.xlsx')->addRows($users)->toBrowser();

```

It not working !!! PLS Help

**Comment by riasvdv** [comment]
Could you post a full stacktrace or a share of the error? That will help us help you

**Comment by agobari** [comment]
```
 $users = DB::table('users')
              ->join('delegates', 'users.user_id', '=', 'delegates.user_id')
              ->select('users.user_first_name_ar','users.user_second_name_ar','users.user_third_name_ar','users.user_last_name_ar', 'delegates.country as delegates_country', 'delegates.province as delegates_province')
            ->get()->toArray();
        
        $writer = SimpleExcelWriter::streamDownload('delegates.xlsx')->addRows($users)->toBrowser();
```

Where $users  is array of stdClass Objects 
`Array ( [0] => stdClass Object ( [user_first_name] => A [user_second_name] => B [user_last_name] => C  ) [1] => stdClass Object ( [user_first_name] => E [user_second_name] => F [user_last_name] => G ) [2] => stdClass Object ( [user_first_name] => H [user_second_name] => I [user_last_name] => J )`

When run code it just return 
Response : 500 Internal Server Error
Header : Content-Disposition: attachment; filename="delegates.xlsx"

But if I just change $users  to array Of arrays 
```
$users = [
        [
            'first_name' => 'John',
            'last_name' => 'Doe',
        ],
        [
            'first_name' => 'Jane',
            'last_name' => 'Doe',
        ],
    ]
```
Everything works fine

**Comment by riasvdv** [comment]
`addRows` only accepts an array of arrays, make sure your `$users` does not contain objects, you can solve this by using `->map` to cast the objects to arrays
