### ISSUE TITLE
Not able to write an excel file to the browser

### ISSUE THREAD

**Issue by travisobregon** [spatie/simple-excel#6]
Are you interested in having the feature to be able to download directly to the browser?

If so, does it make sense to update the constructor of SimpleExcelWriter to have the following?

```php
dirname($path) === '.'
    ? $this->writer->openToBrowser($path)
    : $this->writer->openToFile($path);
```

 Is it okay to assume that a file should be opened to the browser if only a filename is passed to the `create` method or would you add another method like `createToBrowser` or `openToBrowser`?

**Comment by freekmurze** [comment]
> Are you interested in having the feature to be able to download directly to the browser?

Thank you for your suggestion, but probably not. I want to keep this package very small.
