### ISSUE TITLE
Read from request body

### ISSUE THREAD

**Issue by sgtlambda** [spatie/simple-excel#8]
It would be lovely to be able to read from the request body - `php://input` and such. As of right now this isn't possible without a "workaround" of sorts given that the `\Spatie\SimpleExcel\SimpleExcelReader` constructor internally invokes `ReaderEntityFactory::createReaderFromFile` which uses the extension in the filename in order to determine the appropriate reader implementation.

To get around this I've made this terribly hacky class:

```php
<?php

namespace App\Common;

use Spatie\SimpleExcel\SimpleExcelReader as BaseReader;

/**
 * This class wraps SimpleExcelReader in order to be able to manually specify the reader type,
 * as the underlying class normally infers the appropriate reader type from the filename given,
 * which doesn't work for `php://input`.
 * @package App\Common
 */
class SimpleExcelReader extends BaseReader
{

    public function __construct (string $path, string $extension)
    {
        // Provide a dummy filename to the parent constructor because it will
        // immediately instantiate a writer based on the provided filename.
        parent::__construct('_.' . $extension);

        // After the parent constructor has finished, we will replace the value of
        // the "path" property with the "actual" file path passed to this constructor.
        $pathProperty = (new \ReflectionObject($this))->getParentClass()->getProperty('path');
        $pathProperty->setAccessible(true);
        $pathProperty->setValue($this, $path);
        $pathProperty->setAccessible(false);
    }
}
```

Which allows me to do `new SimpleExcelReader('php://input', 'csv');`

Which I'm sure we can all agree isn't ideal :)

I'm happy to submit a PR that would, for instance, have the `\Spatie\SimpleExcel\SimpleExcelReader` constructor take an additional optional argument - either a string or a `\Box\Spout\Reader\ReaderInterface` implementation.

Is that something that would fit the idea of the project?

**Comment by freekmurze** [comment]
Thank you for the idea, but I'd like to keep this package as simple as it can. I've got no need for this functionality, so I'm probably not going to include it.
