### ISSUE TITLE
Openspout Openspout Version Upgrade Request

### ISSUE THREAD

**Issue by shakeel2717** [spatie/simple-excel#92]
Please Upgrade the Required Version openspout/openspout to v4 +.
because i'm using livewire Power-Components/livewire-powergrid package. and i can't install spatie/simple-excel/ because this error appearing.

#Problem 1
    - Root composer.json requires spatie/simple-excel ^2.1 -> satisfiable by spatie/simple-excel[2.1.0].
    - spatie/simple-excel 2.1.0 requires openspout/openspout ^3.0 -> found openspout/openspout[v3.4.0, ..., 3.x-dev] but the package is fixed to v4.6.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

I talked with Power-Components/livewire-powergrid package team, they said this solution
I think the only solution would be fast-excel and simple-excel to support openspout version 4.0.

Thanks

**Comment by ankurk91** [comment]
see https://github.com/spatie/simple-excel/pull/90

**Comment by shakeel2717** [comment]
when will the spatie/simple-excel support V4?
i can't user latest package with spatie/simple-excel. 
 "require": {
        "php": "^8.0",
        "openspout/openspout": "^3.0",
        "illuminate/support": "^8.71|^9.0"
    },
see. there's still version 3.0 required.

**Comment by freekmurze** [comment]
We'll review it the PR when we have some time.
