### ISSUE TITLE
streamDownload not working as expected

### ISSUE THREAD

**Issue by pintend** [spatie/simple-excel#93]
- simple-excel Version: 2.1
- filamentphp: 2.14
- Laravel version: 9.21.5
- PHP Version: 8.1.7

### Description:
Note: i am using this with filamentphp (export file in action)

```php
SimpleExcelWriter::streamDownload($fileName,  $type)
    ->addRows($rows)
    ->toBrowser();
```
#### Issue 1:
The file doesn't download in the browser, if i look at my network tab i can see the contents in the response but wont save as a file

#### Issue 2: 
I can't seem to get this to work with type csv

#### Issue 1 "fix":
```php
$stream = SimpleExcelWriter::streamDownload($fileName,  'xlsx')
    ->addRows($rows)

return response()->streamDownload(function () use ($stream) {
    $stream->close();
}, $fileName):
```

#### Issue 2 "fix": 
```php
return response()->streamDownload(function () use ($rows) {
    SimpleExcelWriter::streamDownload('php://output', 'csv')
        ->addRows($rows)
        ->close();
}, $fileName):
```

**Comment by freekmurze** [comment]
Feel free to PR that fixes. If possible add tests too.
