### ISSUE TITLE
Set a delimeter

### ISSUE THREAD

**Issue by carlosoberto88** [spatie/simple-excel#95]
Hello, 

I'm trying to import a CSV file with over 100000 records, with the following function (I'm only testing so far): 

$rows = SimpleExcelReader::create($pathToCsv)->getRows();

        $rows->each(function (array $rowProperties) {
            dd($rowProperties);
        });

But the CSV has a ; as delimeter and not a comma, so the function is showing me this:

<img width="939" alt="Screenshot 2022-08-01 162302" src="https://user-images.githubusercontent.com/19641157/182249144-116a9f1d-171c-488e-b6d4-9e31b1fbd40a.png">

If i change the delimeter to a comma the function works perfectly, so I was wondering if there is a way to change the delimeter option when I start to import the CSV?

**Comment by freekmurze** [comment]
The reader has this function to change the delimiter: https://github.com/spatie/simple-excel/blob/023e3cbffce554d1bc98d4a6d6fbbcd76598eb5f/src/SimpleExcelReader.php#L81
