### ISSUE TITLE
Encode UTF-8

### ISSUE THREAD

**Issue by carlosoberto88** [spatie/simple-excel#96]
Hello, 

I need to upload a file with some special characters (ñ and áéíóu) and when the simple reader tries to process the file it gives some error in the files. Is there a way to set the encoding to UTF-8 when I'm uploading a file?

**Comment by palpalani** [comment]
We did like this:

```php
SimpleExcelReader::create($pathToFile)
            ->take(100)
            ->noHeaderRow()
            ->map(fn ($row) => mb_convert_encoding($row, 'UTF-8', 'UTF-8'))
            ->toArray();
```
